### ISSUE TITLE
Error running script with default parameter

### ISSUE THREAD

**Issue by ayiz09** [mgeeky/msidump#1]
Hi I have a problem running it with just plain parameter.
I have follow the requirements from the txt

`python msidump.py C:\xxx.msi --debug:`

[dbg] Initializing COM and instantiating WindowsInstaller.Installer ...
[dbg] Opening database C:\Users\Desktop\xxx.msi ...
[dbg] Collected 20 entries from CustomAction ...
[dbg] Collected 43 entries from InstallExecuteSequence ...
[dbg] Collected 22 entries from InstallUISequence ...
[dbg] Parsing CustomAction WixUIPrintEula ...
[dbg] Parsing CustomAction CheckCPUArchitecture ...
[dbg] Parsing CustomAction SetWIX_IS_NETFRAMEWORK_452_OR_LATER_INSTALLED ...
[dbg] Parsing CustomAction SetConditionalProductName ...
[dbg] Parsing CustomAction SetProductName ...
[dbg] Parsing CustomAction SetARPINSTALLLOCATION ...
[dbg] Parsing CustomAction SetConfigureURIs ...
[dbg] Parsing CustomAction ConfigureURIs ...
[dbg] Parsing CustomAction SetSetAccount ...
[dbg] Parsing CustomAction SetAccount ...
[dbg] Parsing CustomAction SetConfigureProxy ...
[dbg] Parsing CustomAction ConfigureProxy ...
[dbg] Parsing CustomAction SetVerifyNetwork ...
[dbg] Parsing CustomAction VerifyNetwork ...
[dbg] Parsing CustomAction SetConfigureService ...
[dbg] Parsing CustomAction ConfigureService ...
[dbg] Parsing CustomAction SetUninstallService ...
[dbg] Parsing CustomAction UninstallService ...
[dbg] Parsing CustomAction SetRollbackService ...
[dbg] Parsing CustomAction RollbackService ...
[dbg] Collected 9 entries from Binary ...
[dbg] Collected 20 entries from CustomAction ...
[dbg] Unsupported column type: table _Streams, column: 2. Type: V0, Name: Data
[dbg] Collected 14 entries from _Streams ...
Traceback (most recent call last):
  File "msidump.py", line 1913, in <module>
    main()
  File "msidump.py", line 1900, in main
    report = processFile(args, args.infile)
  File "msidump.py", line 1845, in processFile
    rep = msir.analyse()
  File "msidump.py", line 681, in analyse
    ret = self.analysisWorker()
  File "msidump.py", line 1198, in analysisWorker
    self.lookForIOCs()
  File "msidump.py", line 1530, in lookForIOCs
    sniffed = self.sniffDataType(data['data'], color=True)
  File "msidump.py", line 1442, in sniffDataType
    magicOut = magic.from_buffer(data, mime=mime)
  File "C:\Python37\lib\site-packages\magic\magic.py", line 147, in from_buffer
    return m.from_buffer(buffer)
  File "C:\Python37\lib\site-packages\magic\magic.py", line 79, in from_buffer
    return maybe_decode(magic_buffer(self.cookie, buf))
  File "C:\Python37\lib\site-packages\magic\magic.py", line 263, in magic_buffer
    return _magic_buffer(cookie, buf, len(buf))
ctypes.ArgumentError: argument 2: <class 'ValueError'>: embedded null character

**Comment by mgeeky** [comment]
Looks like data fingerprinting handled by `magic` fails somehow. I shall surround it with try..catch to prevent these errors.

**Comment by mgeeky** [comment]
Sorry, didn't mean to close it. It was a misclick. Can you try it now?

**Comment by ayiz09** [comment]
Great!! I can use now, Thanks for the fix.
