### ISSUE TITLE
Mention the other tool named msidump

### ISSUE THREAD

**Issue by 3niol4** [mgeeky/msidump#2]
This tool looks great, I'm looking forward to trying it. Quick note though, there is already a (Linux-based) tool called `msidump`, part of the [msitools](https://wiki.gnome.org/msitools) package. It's not a problem, but it would be worth mentioning in your README.

**Comment by mgeeky** [comment]
Hi @3niol4 , thanks for opening this issue. Well, I admit it, when naming my tool I didn't check if one's already available.

The previous one is now mentioned in README.

Thanks!
